name: Deploy to Staging

on:
  push:
    branches:
      - staging   # only deploy when staging branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} "
            cd ~/apps/staging_project || exit 1

            if [ ! -d .git ]; then
              git clone git@github.com:ezifydevelopers/trainportalbackend.git .
            fi

            git fetch --all
            git reset --hard origin/staging

            # Install dependencies
            npm install --production

            # Restart app with pm2
            pm2 restart staging || pm2 start server.js --name staging --watch
          "
